"""Home — landing page with Explore/Compare navigation and policy expanders."""

from __future__ import annotations

import streamlit as st

from src.ui.glossary import HOW_IT_WORKS_EXTRA
from src.ui.privacy import PRIVACY_EXPANDER_BODY
from src.ui.sidebar import init_session_state
from src.ui.theme import page_header

init_session_state()

page_header(
    "Ethical Decision Simulator",
    "Test how AI models reason through moral dilemmas, surface alignment risks, "
    "and compare transparent ethical judgments.",
    show_icon=True,
)

col1, col2 = st.columns(2, gap="large")

with col1:
    st.markdown(
        """
        <div class="card card-accent card-nav card-nav-explore">
        <div class="card-nav-header">
        <span class="card-emoji" aria-hidden="true">🔍</span>
        <h3>Explore</h3>
        </div>
        <p>
        Walk through a single dilemma with reasoning steps, creative alternatives,
        and an ethics primer. View results on screen — use Compare for JSON export.
        </p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    if st.button("Go to Explore", use_container_width=True, key="nav_explore"):
        st.switch_page("pages/explore.py")

with col2:
    st.markdown(
        """
        <div class="card card-accent card-nav card-nav-compare">
        <div class="card-nav-header">
        <span class="card-emoji" aria-hidden="true">📊</span>
        <h3>Compare</h3>
        </div>
        <p>
        Run multiple models side-by-side, stress-test ethical lenses, measure
        agreement and consistency, and export audit JSON.
        </p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    if st.button("Go to Compare", use_container_width=True, key="nav_compare"):
        st.switch_page("pages/compare.py")

with st.expander("How it works", expanded=False):
    steps = [
        ("Choose a dilemma", "Pick a curated scenario or write your own."),
        ("Run a model", "Groq cloud models analyze the dilemma with structured output."),
        ("Review the output", "See the decision, alternatives, reasoning, and framework."),
        ("Compare & audit", "Measure cross-model disagreement and framing sensitivity."),
    ]
    for i, (title, desc) in enumerate(steps, 1):
        st.markdown(f"**{i}. {title}** — {desc}")
    st.markdown(
        "**Rate limits:** If Groq is busy or rate-limited, the app switches to a clearly "
        "labeled **simulated response** so you can keep exploring. "
        "If the service is rate-limited, wait a moment and try again."
    )
    st.markdown(HOW_IT_WORKS_EXTRA)

with st.expander("Privacy & data", expanded=False):
    st.markdown(PRIVACY_EXPANDER_BODY)

st.markdown(
    '<p class="disclaimer">Educational auditing tool only — not moral guidance, legal advice, '
    "or a crisis service. Model outputs are generated by third-party LLMs and may be wrong. "
    "The developer is not responsible for decisions users make based on this tool. "
    "If you are in crisis, call or text <strong>988</strong> (US).</p>",
    unsafe_allow_html=True,
)
