[theme]
base = "light"
primaryColor = "#818CF8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#312E81"
textColor = "#0F172A"
font = "sans serif"

[theme.sidebar]
borderColor = "#FFFFFF"
showWidgetBorder = true

[server]
headless = true

[browser]
gatherUsageStats = false
